# ===================================
#  Relation Behavior Config
# ===================================

categories:
    label: Categories
    view:
        list: $/rainlab/blog/models/category/columns.yaml
        toolbarButtons: create|add
    manage:
        form: $/rainlab/blog/models/category/fields.yaml

series:
    label: Series
    view:
        list: $/ginopane/blogtaxonomy/models/series/columns.yaml
        form: $/ginopane/blogtaxonomy/models/series/fields_simple.yaml
        toolbarButtons: create|link|unlink
    manage:
        form: $/ginopane/blogtaxonomy/models/series/fields_simple.yaml